from __future__ import annotations

import aws_cdk.aws_secretsmanager as sm
from constructs import Construct

from config.models.secrets_manager import SecretConfig
from services.secrets_manager.types.base import BaseSecretType


class GeneratedSecret(BaseSecretType):
    """
    Creates an AWS Secrets Manager secret whose value is auto-generated by AWS
    at deploy time using ``SecretStringGenerator``.

    No value is ever specified in config, code, or CI/CD — AWS generates a
    cryptographically strong random string according to the ``generate`` rules
    defined in the YAML config block.

    The generated value can be retrieved at runtime via the AWS SDK:
        boto3.client("secretsmanager").get_secret_value(SecretId=name)

    Typical use: database passwords, internal service tokens, encryption keys
    that do not need to match a pre-existing external value.
    """

    def create(self, scope: Construct, config: SecretConfig) -> None:
        g = config.generate_config
        sm.Secret(
            scope,
            "Resource",
            secret_name=config.name,
            description=config.description or None,
            generate_secret_string=sm.SecretStringGenerator(
                password_length=g.length,
                exclude_characters=g.exclude_characters or None,
                exclude_punctuation=g.exclude_punctuation,
            ),
        )
