from __future__ import annotations

import aws_cdk.aws_secretsmanager as sm
from constructs import Construct

from config.models.secrets_manager import SecretConfig
from services.secrets_manager.types.base import BaseSecretType


class GeneratedSecret(BaseSecretType):
    """
    Creates an AWS Secrets Manager secret whose value is auto-generated by AWS
    at deploy time using ``SecretStringGenerator``.

    No value is ever specified in config, code, or CI/CD — AWS generates a
    cryptographically strong random string according to the ``generate`` rules
    defined in the YAML config block.

    Supports the full ``SecretStringGenerator`` field set:

      - ``length``, ``exclude_characters``, ``exclude_punctuation``:
        Character set and length controls.
      - ``include_space``: Allow spaces in the generated value.
      - ``require_each_included_type``: Guarantee uppercase, lowercase,
        digit, and symbol all appear.
      - ``secret_string_template`` + ``generate_string_key``:
        Generate a JSON-structured secret compatible with RDS/Aurora
        automatic rotation, e.g.::

            secret_string_template: '{"username": "admin"}'
            generate_string_key: "password"
            # Result stored: {"username": "admin", "password": "<generated>"}

    Supports tags, removal policy, KMS encryption, and cross-region replication.

    Typical use: database passwords, internal service tokens, encryption keys
    that do not need to match a pre-existing external value.
    """

    def create(self, scope: Construct, config: SecretConfig) -> None:
        g = config.generate_config
        encryption_key = self._resolve_kms_key(scope, config)
        replica_regions = self._build_replica_regions(config)

        generator = sm.SecretStringGenerator(
            password_length=g.length,
            exclude_characters=g.exclude_characters or None,
            exclude_punctuation=g.exclude_punctuation,
            include_space=g.include_space,
            require_each_included_type=g.require_each_included_type,
            secret_string_template=g.secret_string_template or None,
            generate_string_key=g.generate_string_key or None,
        )

        secret = sm.Secret(
            scope,
            "Resource",
            secret_name=config.name,
            description=config.description or None,
            generate_secret_string=generator,
            encryption_key=encryption_key,
            replica_regions=replica_regions,
        )
        self._apply_managed_secret_fields(secret, config)
