# gh action to run manual deployment

name: Run Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        required: true
        type: string
        default: "dev"
      module:
        description: The module to deploy
        required: true
        type: string
        default: "aws"

jobs:
    setup_python:
        runs-on: ubuntu-latest
        steps:
            - name: install python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
    setup_environment:
        runs-on: ubuntu-latest
        needs: [setup_python]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: nstall dependencies
              run: |
                pip install -r ./${{ inputs.module }}/requirements.txt
            
            
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
    
    